### ISSUE TITLE
建议修改判断服务器故障的时候间隔n秒ping m次，m次都失败作为服务器失效的入口条件

### ISSUE THREAD

**Issue by zhbbo08** [BlueSkyXN/DNS-AUTO-Switch#1]
当前脚本只检测一次，存在一定的偶然性。建议定义一下多次ping

**Comment by BlueSkyXN** [comment]
1，间隔时间取决你自己，定时任务1S，1M，1H都可以
2，这个ping并不是ICMPing，而是TCP【由go-torch提供服务】，理论上TCPing是很难出现丢失的【在国际带宽的情况下】，（概率极低，一般低于1%）如果你经常TCPing失败，说明其他使用者也会出现这种情况，请调整你的服务器和监控器
3，如何修改的话，可以提供简单的修改思路
以hw.sh为例，实现每次检测2次，在代码第96行：CHECK=$(curl -s "$PING_API/$ORG_IP/22")
有意思变量CHECK设置为后面地址的内容，你可以再加个CHECK2，也等于这个，这样就等于测2次了
第98行：if [ "$(echo $CHECK | grep "\"status\":true")" != "" ]
意思当CHECK这个变量中，出现字段status:true的时候触发下面内容，否则干嘛干嘛（基本IF语法）
套娃个IF 什么什么CHECK2什么什么即可
【99-110是第一次状态正常，112开始是第一次不正常，在那边加上双重IF即可】




> 当前脚本只检测一次，存在一定的偶然性。建议定义一下多次ping
